new_relic:
  key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>

attr_encrypted:
  key: <%= ENV['ATTR_ENCRYPTED_KEY'] %>

google_maps_embed:
  key: <%= ENV['GOOGLE_MAPS_EMBED_API_KEY'] %>

google_geocode:
  key: <%= ENV['GOOGLE_GEOCODE_API_KEY'] %>

smtp_config:
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  address: <%= ENV['SMTP_ADDRESS'] %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  port: <%= ENV['SMTP_PORT'].to_i %>
  authentication: <%= ENV['SMTP_AUTH'] %>

default_url:
  host: <%= ENV['URL_HOST'] %>
  port: <%= ENV['URL_PORT'].to_i %>

cdn:
  host: <%= ENV['CDN_HOST'] %>

cors:
  origins: <%= ENV.fetch('CORS_ORIGINS', '').split(',') %>

rack_timeout:
  seconds: <%= ENV.fetch('TIMEOUT', 5).to_i %>

donations:
  address: <%= ENV['DONATION_ADDRESS'] %>
  qr_code: <%= ENV['DONATION_QR_CODE'] %>
